name: KamynsFlix
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.5"
settings:
  base:
    MARKETING_VERSION: "2.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  KamynsFlix:
    type: application
    platform: iOS
    deploymentTarget: "15.5"
    sources:
      - path: Sources
    resources:
      - path: Sources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.median.ios.qdlejpp
        PRODUCT_NAME: KamynsFlix
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
